aws:
  s3:
    mock: false

spring:
  datasource:
    url: jdbc:postgresql://awseb-e-2i2vbmp8th-stack-awsebrdsdatabase-v0iiz0ipilny.cuojv6x4pu5b.us-east-1.rds.amazonaws.com:5432/ebdb
    username: skynet
    password: 12345678